### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/opt/ml/model/model.pth'

### ISSUE THREAD

**Issue by JTHEN-DEV** [aws-samples/end-to-end-object-detection-detectron2-sagemaker#1]
I am using my own `model.pth` file and I've followed the structure that is stated and uploaded it to an s3 bucket. However, when I run the inference ipynb file, all goes smoothly until `remote_model.deploy`. After around 20 minutes the following error message occurs:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\<USER>\AppData\Local\Programs\Python\Python38\lib\site-packages\sagemaker\model.py", line 524, in deploy
    self.sagemaker_session.endpoint_from_production_variants(
  File "C:\Users\<USER>\AppData\Local\Programs\Python\Python38\lib\site-packages\sagemaker\session.py", line 3193, in endpoint_from_production_variants
    return self.create_endpoint(endpoint_name=name, config_name=name, tags=tags, wait=wait)
  File "C:\Users\<USER>\AppData\Local\Programs\Python\Python38\lib\site-packages\sagemaker\session.py", line 2711, in create_endpoint
    self.wait_for_endpoint(endpoint_name)
  File "C:\Users\<USER>\AppData\Local\Programs\Python\Python38\lib\site-packages\sagemaker\session.py", line 2975, in wait_for_endpoint
    raise exceptions.UnexpectedStatusException(
sagemaker.exceptions.UnexpectedStatusException: Error hosting endpoint model-deploy: Failed. Reason:  The primary container for production variant AllTraffic did not pass the ping health check. Please check CloudWatch logs for this endpoint..
```

I checked the cloud logs which gave the following:
```
Traceback (most recent call last):
  File "/opt/conda/bin/torch-model-archiver", line 10, in <module>
    sys.exit(generate_model_archive())
  File "/opt/conda/lib/python3.6/site-packages/model_archiver/model_packaging.py", line 60, in generate_model_archive
    package_model(args, manifest=manifest)
  File "/opt/conda/lib/python3.6/site-packages/model_archiver/model_packaging.py", line 37, in package_model
    model_path = ModelExportUtils.copy_artifacts(model_name, **artifact_files)
  File "/opt/conda/lib/python3.6/site-packages/model_archiver/model_packaging_utils.py", line 150, in copy_artifacts
    shutil.copy(path, model_path)
  File "/opt/conda/lib/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/conda/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
```
AND
```
FileNotFoundError: [Errno 2] No such file or directory: '/opt/ml/model/model.pth'
```
Repeated over and over again. I'm not sure what is wrong here...

**Comment by JTHEN-DEV** [comment]
This initial error was mitigated through changing the `framework_version` in `d2_inference.ipynb` from "1.6.0" to "1.5.0" i.e.:
```
remote_model = PyTorchModel(
                     name = model_name, 
                     model_data=model_url,
                     role=role,
                     sagemaker_session = sess,
                     entry_point="inference.py",
                     # image=image, 
                     framework_version="1.6.0",
                     py_version='py3'
                    )
```
to
```
remote_model = PyTorchModel(
                     name = model_name, 
                     model_data=model_url,
                     role=role,
                     sagemaker_session = sess,
                     entry_point="inference.py",
                     # image=image, 
                     framework_version="1.5.0",
                     py_version='py3'
                    )
```

**Comment by JTHEN-DEV** [comment]
Still has an error with file `Base-RCNN-FPN.yaml` not found, because the folder structure in the instructions on the README (in the "Bring Your Own `model.pth` Workflow to Deploy" section), so I didn't include it. I'm testing it now with the included `Base-RCNN-FPN.yaml` and will get back to you on results with this new change

**Comment by JTHEN-DEV** [comment]
The endpoint is up and running, but invoking it gives the following issue:
```
ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500) from model with message "local variable 'pred' referenced before assignment". See ARN in account ID for more information.
```

**Comment by JTHEN-DEV** [comment]
I have resolved this. It was an issue with my `config.yaml` file. So sorry about that!

**Comment by gucciwang** [comment]
Glad it worked out for you! :) Let me know if there are any documentation/pointers that you could've benefited more from :)

**Comment by JTHEN-DEV** [comment]
I don't know the details surrounding how to add this, but my initial error of `No such file or directory: '/opt/ml/model/model.pth'` was solved through changing:
```
remote_model = PyTorchModel(
                     name = model_name, 
                     model_data=model_url,
                     role=role,
                     sagemaker_session = sess,
                     entry_point="inference.py",
                     # image=image, 
                     framework_version="1.6.0",
                     py_version='py3'
                    )
```
to
```
remote_model = PyTorchModel(
                     name = model_name, 
                     model_data=model_url,
                     role=role,
                     sagemaker_session = sess,
                     entry_point="inference.py",
                     # image=image, 
                     framework_version="1.5.0",
                     py_version='py3'
                    )
```
i.e. setting the framework version to 1.5.0 rather than 1.6.0, which for some reason solved the problem. Other than that I think the documentation is fantastic!

**Comment by JTHEN-DEV** [comment]
Just remembered, also the model_url that you set for the s3 bucket apparently has to contain the keyword sagemaker, or else a new bucket is created? That's what happened to me anyway

**Comment by gucciwang** [comment]
I think changing the PyTorch version from 1.6.0 -> 1.5.0 may have been to comply with the training environment for when you trained your model -- can you double check your training environment's PyTorch version for me? Would love to clarify. 

Regarding the keyword "sagemaker" being in the model_url S3 path, you are correct! The default permissions given to a SageMaker role only allows it to touch S3 buckets that have the keyword "sagemaker" in its name. I built this workflow with the principle of least privilege in mind, but good finding!

**Comment by JTHEN-DEV** [comment]
You are 100% right! I just checked and I did use PyTorch 1.5.0 so I know see why I would have gotten that error! Thanks so much!

**Comment by JTHEN-DEV** [comment]
If there was a kudos system for Github, I would 100% give you kudos or points or whatever : )

**Comment by gucciwang** [comment]
Haha thanks! Happy to help :)
